[tool.poetry]
name = "qualityqueue"
version = "0.0.1"
description = "tbd"
authors = ["DyMattic <dymattic@naise.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
librosa = "^0.10.2.post1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
